-   id: make-some-noise
    name: Make Some Noise
    description: (Currently windows only) Plays a sound if the other hooks all passed, 
    entry: make_some_noise.py
    language: script
    files: '.*'