default_language_version:
  python: python3.12
  
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ "--line-length=88", "--profile=black" ]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [ "--line-length=88" ]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: [ "--max-line-length=88" ]
  - repo: .
    rev: HEAD
    hooks:
      - id: make-some-noise
        args: []

exclude: |
  (?x)(
    ^folder/to/ignore|
    ^file_to_ignore.py
  )